colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "basic"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = true
  sharingLinks = ["x-twitter", "linkedin", "reddit", "email"]

[list]
  showSummary = true
  groupByYear = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
